package hello;
// Generated Mar 6, 2017 4:57:02 PM by Hibernate Tools 4.3.1



/**
 * Info generated by hbm2java
 */
public class Info  implements java.io.Serializable {


     private String firstName;
     private String lastName;
     private String email;
     private String phone;
     private String location;

    public Info() {
    }

    public Info(String firstName, String lastName, String email, String phone, String location) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.email = email;
       this.phone = phone;
       this.location = location;
    }
   
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }




}


